# Generated by Django 3.2.6 on 2021-08-14 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otherrealms', '0002_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='poster',
        ),
    ]
