# Generated by Django 3.2.6 on 2021-08-14 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otherrealms', '0003_remove_post_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='psot_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
