# Generated by Django 3.2.6 on 2021-08-14 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otherrealms', '0004_post_psot_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='psot_image',
            new_name='post_image',
        ),
    ]
