# Generated by Django 3.2 on 2021-08-20 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otherrealms', '0006_imagelink'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=64)),
                ('event_content', models.TextField(blank=True)),
                ('event_image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
