# Generated by Django 3.2.6 on 2021-08-21 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otherrealms', '0008_calendarevent_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='event_date',
            field=models.DateField(),
        ),
    ]
