# Generated by Django 3.2.6 on 2021-09-11 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_productmodel_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='availability',
            field=models.IntegerField(default=0),
        ),
    ]
